"use strict";
exports.__esModule = true;
var NOS_PICKER_MODE;
(function (NOS_PICKER_MODE) {
    NOS_PICKER_MODE[NOS_PICKER_MODE["SINGLE"] = 0] = "SINGLE";
    NOS_PICKER_MODE[NOS_PICKER_MODE["MULTI"] = 1] = "MULTI";
    NOS_PICKER_MODE[NOS_PICKER_MODE["STRING"] = 2] = "STRING";
})(NOS_PICKER_MODE = exports.NOS_PICKER_MODE || (exports.NOS_PICKER_MODE = {}));
var NOS_PICKER_STATE;
(function (NOS_PICKER_STATE) {
    NOS_PICKER_STATE[NOS_PICKER_STATE["INIT"] = 0] = "INIT";
    NOS_PICKER_STATE[NOS_PICKER_STATE["SELECTED"] = 1] = "SELECTED";
    NOS_PICKER_STATE[NOS_PICKER_STATE["SEARCH"] = 2] = "SEARCH";
})(NOS_PICKER_STATE = exports.NOS_PICKER_STATE || (exports.NOS_PICKER_STATE = {}));
